[package]
name = "code-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.57"
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
web-sys = "0.3.57"
yew = "0.19.3"
